[package]
name = "wfc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wfc-generator"

[[bin]]
name = "simple-input"

[[bin]]
name = "load-backup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
rand = "0.8.5"